# Generated by Django 4.2.3 on 2023-07-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_product_farmer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImages',
        ),
    ]
