# Generated by Django 4.2.3 on 2023-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0007_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
