# Generated by Django 4.2.3 on 2023-07-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0009_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product_images'),
        ),
    ]
