# Generated by Django 4.2.3 on 2023-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0011_alter_cartorder_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
