# Generated by Django 4.2.3 on 2023-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0013_alter_cartorder_paid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='order_date',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='paid_status',
            new_name='paid_status_order',
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
