# Generated by Django 4.2.3 on 2023-07-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0015_rename_order_cartorder_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='paid_status',
        ),
    ]
